function Rxgreen = LoRa_data_import_func_test3(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RXGREEN = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  RXGREEN = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Rxgreen = importfile("C:\Users\s153480\Documents\GitHub\Graduation-project\data\LoRa_trilateration_test_3\Rx_green.TXT", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-May-2022 16:26:20

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ", ",", ":"];

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "VarName4", "VarName5", "VarName6", "Var7", "VarName8", "VarName9", "VarName10", "Var11", "VarName12", "VarName13", "VarName14", "Var15", "VarName16", "VarName17", "VarName18", "Var19", "Var20", "Var21", "VarName22"];
opts.SelectedVariableNames = ["VarName4", "VarName5", "VarName6", "VarName8", "VarName9", "VarName10", "VarName12", "VarName13", "VarName14", "VarName16", "VarName17", "VarName18", "VarName22"];
opts.VariableTypes = ["string", "string", "string", "double", "double", "double", "string", "double", "double", "double", "string", "double", "double", "double", "string", "double", "double", "double", "string", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var7", "Var11", "Var15", "Var19", "Var20", "Var21"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var7", "Var11", "Var15", "Var19", "Var20", "Var21"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "VarName5", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName5", "ThousandsSeparator", ",");

% Import the data
Rxgreen = readtable(filename, opts);

%% Convert to output type
Rxgreen = table2array(Rxgreen);
end