function RB = LoRa_data_import_func(filename, dataLines)
%IMPORTFILE Import data from a text file
%  RB = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the numeric data.
%
%  RB = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  RB = importfile("C:\Users\Bram\Documents\GitHub\Graduation-project\data\test_session\RB.TXT", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 05-Apr-2022 13:55:45

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [" ", "_"];

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "VarName3", "packet", "Var5", "VarName6", "Var7", "Var8", "VarName9"];
opts.SelectedVariableNames = ["VarName3", "packet", "VarName6", "VarName9"];
opts.VariableTypes = ["string", "string", "double", "double", "string", "double", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var5", "Var7", "Var8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var5", "Var7", "Var8"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "packet", "TrimNonNumeric", true);
opts = setvaropts(opts, "packet", "ThousandsSeparator", ",");

% Import the data
RB = readtable(filename, opts);

%% Convert to output type
RB = table2array(RB);
end